apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ app_name }}
    team: {{ team_name }}
  name: {{ app_name }}
  namespace: {{ team_name }}
spec:
  type: ExternalName
  externalName: storage.googleapis.com
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
