name: "Upload to CDN"
description: "Upload static assets to Frontend Plattform CDN"
inputs:
  cdn-environment:
    description: "CDN environment name (cdn.dev.nav.no or cdn.nav.no)"
    required: false
    default: "cdn.nav.no"
  cdn-team-name:
    description: "CDN team name"
    required: true
  source:
    description: "Source directory"
    required: true
  source-keep-parent-name:
    description: "Keep parent directory name when uploading"
    required: false
    default: "true"
  destination:
    description: "Destination directory"
    required: true
  cache-invalidation:
    description: "Cache invalidation"
    required: false
    default: "false"
  cache-invalidation-background:
    description: "Run cache invalidation in the background without waiting"
    required: false
    default: "true"
  no-cache-paths:
    description: "Comma separated list of paths that should not be cached"
    required: false
    default: ""

outputs:
  uploaded:
    description: "Uploaded files"
    value: ${{ steps.upload-file.outputs.uploaded }}
runs:
  using: "composite"
  steps:
	  - name: "cdn-upload/v1 removal notice"
      shell: bash
      run: |
        echo "::error ::cdn-upload/v1 has been removed."
        echo "Please upgrade to cdn-upload/v2." >> $GITHUB_STEP_SUMMARY
        echo "Slack thread: https://nav-it.slack.com/archives/C01DE3M9YBV/p1710329765663829" >> $GITHUB_STEP_SUMMARY
        echo "Documentation: https://doc.nais.io/explanation/cdn/" >> $GITHUB_STEP_SUMMARY
        echo "Example: https://github.com/navikt/frontend-golden-path/compare/242b9cd52fa9edb5c9b76acd13eb0e5f5f8740b0...474055584c1abdcb271133f9cab283eaa7b0ebe6" >> $GITHUB_STEP_SUMMARY
        exit 1
