name: 'Deploy SPA'
description: 'Deploy a Single Page Application to CDN and NAIS'
inputs:
  team-name:
    description: 'Team name'
    required: true
  app-name:
    description: 'Application name'
    required: true
  source:
    description: 'Application source directory'
    required: true
  ingress:
    description: 'Application ingress URL'
    required: true
  environment:
    description: 'Environment name'
    required: false
    default: ''

outputs:
  nais-cluster:
    description: 'NAIS cluster name'
  nais-resource:
    description: 'NAIS resource files'
  nais-vars:
    description: 'NAIS variables'
  cdn-destination:
    description: 'CDN destination'

runs:
  using: 'node16'
  main: 'dist/index.js'