name: "React.JS on CDN"

on:
  push:
    branches:
      - 'main'
    paths:
      - 'react/cdn/**'
      - '.github/workflows/react-on-cdn.yaml'
  pull_request:
    paths:
      - 'react/cdn/**'
      - '.github/workflows/react-on-cdn.yaml'

env:
  APP_NAME: fp-react-cdn
  APP_DIR: react/cdn
  APP_BUILD: react/cdn/build
  APP_ENV: labs
  APP_INGRESS: fp-react-cdn.labs.nais.io
  TEAM_NAME: frontendplattform

jobs:
  build-app:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build app
        run: npm run build

      - uses: actions/upload-artifact@master
        name: Upload build artifact
        with:
          name: ${{ env.APP_NAME }}
          path: ${{ env.APP_BUILD }}


  deploy-app:
    runs-on: ubuntu-latest

    needs: build-app

    # if: github.ref == 'refs/heads/main'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: ${{ env.APP_NAME }}
          path: ${{ env.APP_BUILD }}

      - name: SPA deploy
        uses: ./actions/spa-deploy/v1
        with:
          app-name: ${{ env.APP_NAME }}
          team-name: ${{ env.TEAM_NAME }}
          environment: ${{ env.APP_ENV }}
          ingress: ${{ env.APP_INGRESS }}
          source: ${{ env.APP_BUILD }}
          nais-deploy-apikey: ${{ secrets.NAIS_DEPLOY_APIKEY }}
