name: 'SPA Deploy Action'
description: 'Upload Single Page Application (SPA) to CDN and deploy to NAIS'
inputs:
  team:
    description: 'Team name'
    required: true
  app:
    description: 'Application name'
    required: true
  source:
    description: 'Application source directory'
    required: true
  environment:
    description: 'Environment name'
    required: true
  ingress:
    description: 'Application ingress URL'
    required: true
  project_id:
    description: "Google Cloud project ID where buckets are hosted"
    required: true
  identity_provider:
    description: "Google Workload Identity Provider"
    required: true

outputs:
  url:
    description: "SPA URL"
    value: ${{ inputs.ingress }}

runs:
  using: "composite"
  steps:
    - id: setup
      name: Setup for SPA deploy
      uses: navikt/frontend/actions/spa-setup-task@cdn-v2
      with:
        team-name: ${{ inputs.team }}
        app-name: ${{ inputs.app }}
        ingress: ${{ inputs.ingress }}
        source: ${{ inputs.source }}
        environment: ${{ inputs.environment }}

    - id: cdn-upload
      name: Upload SPA to CDN
      uses: nais/deploy/actions/cdn-upload/v2@master
      with:
        team: ${{ inputs.team-name }}
        source: ${{ inputs.source }}
        source_keep_parent_name: false
        destination: ${{ steps.setup.outputs.cdn-destination }}
        project_id: ${{ inputs.project_id }}
        identity_provider: ${{ inputs.identity_provider }}

    - id: nais-deploy
      name: Deploy SPA to NAIS
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: ${{ steps.setup.outputs.nais-cluster }}
        RESOURCE: ${{ steps.setup.outputs.nais-resource }}
        VAR: ${{ steps.setup.outputs.nais-var }}
        TEAM: ${{ inputs.team-name }}
