name: 'SPA Deploy Action'
description: 'Upload Single Page Application (SPA) to CDN and deploy to NAIS'
inputs:
  team-name:
    description: 'Team name'
    required: true
  app-name:
    description: 'Application name'
    required: true
  source:
    description: 'Application source directory'
    required: true
  environment:
    description: 'Environment name'
    required: true
  ingress:
    description: 'Application ingress URL'
    required: true
  nais-deploy-apikey:
    description: 'NAIS deploy API key'
    required: false
    default: ""

outputs:
  url:
    description: "SPA URL"
    value: ${{ inputs.ingress }}

runs:
  using: "composite"
  steps:
    - name: "spa-deploy/v1 removal notice"
      shell: bash
      run: |
        echo "::error ::spa-deploy/v1 has been removed."
        echo "Please upgrade to spa-deploy/v2." >> $GITHUB_STEP_SUMMARY
        echo "Slack thread: https://nav-it.slack.com/archives/C01DE3M9YBV/p1710329765663829" >> $GITHUB_STEP_SUMMARY
        echo "Documentation: https://doc.nais.io/explanation/cdn/" >> $GITHUB_STEP_SUMMARY
        echo "Example: https://github.com/navikt/eldrebolgen/compare/d7223248472ee849e63d1a28dfe4c459d27a1058..3d963519ba1228c3b19fdf82fe99bf30e03e24fb" >> $GITHUB_STEP_SUMMARY
        exit 1
